### ISSUE TITLE
[Q-Mail] Cannot open messages

### ISSUE THREAD

**Issue by TrendyKangaroo** [Qortal/Q-Apps#69]
I'm trying to open the newest message, but it gives me the waiting icon, then never opens. It just kicks back to the main messages screen. I've tried restarting, etc.

**Comment by crowetic** [comment]
This happens if the data cannot be found. But yes, I agree it should give some type of message.

This also happens if the user had sent a message, then changed their name. (I noticed this recently.) 

But yea, if the data cannot be found, it cannot open. But yes, there should be an error that comes up for this I think.

**Comment by TrendyKangaroo** [comment]
Thanks, it started working again.
